server:
  port: 8081

spring:
  application:
    name: account


  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      email: email
      orchestrator: orchestrator
      user-success: product-success
    consumer:
      group-id: account-group
      auto-offset-reset: latest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_POST:5432}/${DB_NAME:account-hotmart}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/oauth2/jwks



logging:
  level:
    org:
      apache:
        kafka: OFF
