server:
  port: 8085

spring:
  application:
    name: payments

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      email: email
      payment-success: payment-success
      payment-fail: payment-fail
      notify-ending: notify-ending
    consumer:
      group-id: payments-group
      auto-offset-reset: latest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:payments-hotmart}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/oauth2/jwks
      client:
        registration:
          account-hotmart:
            provider: ${PROVIDER_NAME}
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: ${AUTHORIZATION_GRANT_TYPE}
            scope: ${SCOPE}
            client-name: ${CLIENT_NAME}
        provider:
          hotmart:
            issuer-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}

logging:
  level:
    org:
      apache:
        kafka: OFF