version: '3'

services:

#  event-db:
#    image: mongo:latest
#    container_name: event-db
#    restart: always
#    networks:
#      - hotmart
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=123456
#    ports:
#      - 27017:27017

#  inventory-db:
#    image: postgres:latest
#    container_name: inventory-db
#    networks:
#      - hotmart
#    environment:
#      - POSTGRES_DB=inventory-db
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - 5434:5432

  kafka:
    container_name: kafka
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - hotmart
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    volumes:
      - ./data/kafka/data:/var/lib/kafka/data

  redpanda-console:
    container_name: redpanda
    image: docker.redpanda.com/vectorized/console:latest
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    ports:
      - "3000:8080"
    networks:
      - hotmart
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:29092"]
    depends_on:
      - "kafka"


#  inventory-service:
#    build: ./inventory-service
#    container_name: inventory-service
#    depends_on:
#      - inventory-db
#      - kafka
#    networks:
#      - hotmart
#    environment:
#      - KAFKA_BROKER=kafka:29092
#      - DB_HOST=inventory-db
#      - DB_PORT=5432
#      - DB_NAME=inventory-db
#      - DB_USERNAME=postgres
#      - DB_PASSWORD=postgres
#    ports:
#      - 8092:8092

networks:
  hotmart:
    driver: bridge
