server:
  port: 8084

spring:
  application:
    name: orders

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      email: email
      product-start: product-start
      notify-ending: notify-ending
    consumer:
      group-id: orders-group
      auto-offset-reset: latest

  data:
    mongodb:
      database: ${MONGO_DB_DATABASE}
      uri: ${MONGO_DB_URI}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/oauth2/jwks
      client:
        registration:
          account-hotmart:
            provider: ${PROVIDER_NAME}
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: ${AUTHORIZATION_GRANT_TYPE}
            scope: ${SCOPE}
            client-name: ${CLIENT_NAME}
        provider:
          hotmart:
            issuer-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}


logging:
  level:
    org:
      apache:
        kafka: OFF