spring:
  application:
    name: auth


  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      email: email
    consumer:
      group-id: auth-group
      auto-offset-reset: latest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_POST:5432}/${DB_NAME:account-hotmart}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


  session:
    jdbc:
      flush-mode: on_save
      initialize-schema: always
    store-type: jdbc

app:
  auth:
    provider-uri: ${PROVIDER_URI}
    jks:
      keypass: ${JKS_KEYPASS}
      storepass: ${JKS_STOREPASS}
      alias: hotmart
      path: keystore/hotmart.jks

logging:
  level:
    org.springframework.session: DEBUG
    org.apache.kafka: OFF
server:
  error:
    path: /error
