package com.hotmart.account.enums;

public enum TemplateType {

    DATA_ACCESS,
    CHANGE_PASSWORD,
    MEMBER_AREA_CREATED,
    TWO_FACTOR_AUTHENTICATED,
    SECURITY_CODE,
    APPROVED_PURCHASE,
    VALIDATED_DATA,
    HOTMART_CLUB,
    PAYMENT_REMINDER_1,
    PAYMENT_REMINDER_2,
    NOT_DEBITED,
    PAYMENT_PIX,
    RECEIVED_ORDER,
    REFUND,
    REFUND_PROCESSED;

}
